### ISSUE TITLE
GitHub flavoured Markdown documentation

### ISSUE THREAD

**Issue by spindev** [xpirit-training/github-training-custom-plusnet#12]
# Heading
### Heading

- item 1
- item 2

1. First entry
2. Second entry
#5 

@aatmmr Here we are collecting all the mark down features.

**Comment by spindev** [comment]
# Table

| Spalte 1 | Spalte 2|
| :---| :--- |
| Eintrag 1 | Eintrag 2|

**Comment by spindev** [comment]
Here is a simple flow chart:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
```

**Comment by AndreFischerPlusnet** [comment]
[Release 4.0.14](https://github.com/plusnet-de/one-portal/releases/tag/4.0.14)

- [ ] Release
- [ ] Rollout
- [ ] Test
