### ISSUE TITLE
GitHub flavoured Markdown documentation

### ISSUE THREAD

**Issue by spindev** [xpirit-training/github-training-custom-plusnet#25]
# General
### Topic 1

- item 1
- item 2

Tasklist

- [ ]  Task 2
- [x] #26
- [ ]  Task 3

**Comment by marcelsiegert** [comment]
Bilder per D&D testen.

![martin-martz-My3Hal_y4FE-unsplash](https://github.com/xpirit-training/github-training-custom-plusnet/assets/66531432/ae179a10-85d0-4521-9e41-58086d5b4c09)

**Comment by spindev** [comment]
Here is a simple flow chart:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

**Comment by c3fr4** [comment]
# Heading

Paragraph
